### PR TITLE
Intitial Stub for Admin and Answer Controller

### PR DESCRIPTION
**Pull request by santosin**
This is pull request for Admin and Answer Controller

### CODE REVIEW

**Comment by bhaskara-iiitb** [comment]
I think the changes have been made directly onto master branch of forked repo. 
Could you please revert the changes from master repo and push the changes in the respective branches "AdminEndpoints" and "AnswerEndpoints"? Then you can resubmit the pull request

**Review by bhaskara-iiitb — CHANGES_REQUESTED** [review]
The changes are made directly on santosin:master branch. Per process the changes should go to the respective feature branches first (AdminEndpoints and AnswerEndpoints)

**Review by sanjaya-panigrahi — APPROVED** [review]
Good to go. AdminController and AnswerController

**Comment by bhaskara-iiitb** [comment]
Duplicated by latest pull request

**Pull request closed without merging**
